import { KitchenState, PantryItem, Recipe, ShoppingItem, PlannedMealItem } from '../types';

export const STORAGE_KEY = 'moja-kuchnia-state-v2';
export const LOW_STOCK_RATIO = 0.25;

export const DEFAULT_CATEGORIES: string[] = [
  'Nabiał',
  'Mięso i ryby',
  'Warzywa',
  'Owoce',
  'Pieczywo',
  'Suche i sypkie',
  'Napoje',
  'Sosy i przyprawy',
  'Mrożonki',
  'Słodycze i przekąski',
  'Inne',
];

// Helper to format date string YYYY-MM-DD
export function formatDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

export function addDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return formatDate(d);
}

export const INITIAL_PANTRY: PantryItem[] = [
  {
    id: 'p1',
    name: 'Mleko 2.0% Świeże',
    zone: 'fridge',
    category: 'Nabiał',
    currentAmount: 200,
    totalAmount: 1000,
    unit: 'ml',
    expiryDate: addDays(4),
    openedAt: formatDate(new Date()),
    daysValidAfterOpen: 3,
    kcalPer100g: 50,
    proteinPer100g: 3.3,
    fatPer100g: 2.0,
    carbsPer100g: 4.8,
    price: 3.89,
    barcode: '5900512300124',
  },
  {
    id: 'p2',
    name: 'Jajka z wolnego wybiegu',
    zone: 'fridge',
    category: 'Nabiał',
    currentAmount: 4,
    totalAmount: 10,
    unit: 'szt',
    expiryDate: addDays(6),
    kcalPer100g: 143,
    proteinPer100g: 12.6,
    fatPer100g: 9.5,
    carbsPer100g: 0.7,
    price: 11.99,
  },
  {
    id: 'p3',
    name: 'Jogurt Grecki 0%',
    zone: 'fridge',
    category: 'Nabiał',
    currentAmount: 80, // <= 25% of 400g! Triggered low stock
    totalAmount: 400,
    unit: 'g',
    expiryDate: addDays(1), // expiring soon!
    kcalPer100g: 59,
    proteinPer100g: 10.3,
    fatPer100g: 0.2,
    carbsPer100g: 4.0,
    price: 4.50,
  },
  {
    id: 'p4',
    name: 'Pomidorki koktajlowe',
    zone: 'fridge',
    category: 'Warzywa',
    currentAmount: 250,
    totalAmount: 250,
    unit: 'g',
    expiryDate: addDays(3),
    kcalPer100g: 18,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    carbsPer100g: 3.9,
    price: 6.99,
  },
  {
    id: 'p5',
    name: 'Pierś z indyka (filet)',
    zone: 'fridge',
    category: 'Mięso i ryby',
    currentAmount: 450,
    totalAmount: 500,
    unit: 'g',
    expiryDate: addDays(2), // 2 days left
    kcalPer100g: 105,
    proteinPer100g: 24.0,
    fatPer100g: 1.0,
    carbsPer100g: 0.0,
    price: 18.50,
  },
  {
    id: 'p6',
    name: 'Krewetki mrożone Black Tiger',
    zone: 'freezer',
    category: 'Mrożonki',
    currentAmount: 350,
    totalAmount: 450,
    unit: 'g',
    expiryDate: addDays(120),
    kcalPer100g: 85,
    proteinPer100g: 19.0,
    fatPer100g: 0.8,
    carbsPer100g: 0.0,
    price: 32.00,
  },
  {
    id: 'p7',
    name: 'Mieszanka warzyw na patelnię',
    zone: 'freezer',
    category: 'Mrożonki',
    currentAmount: 400,
    totalAmount: 400,
    unit: 'g',
    expiryDate: addDays(90),
    kcalPer100g: 45,
    proteinPer100g: 2.2,
    fatPer100g: 0.5,
    carbsPer100g: 7.2,
    price: 7.20,
  },
  {
    id: 'p8',
    name: 'Płatki owsiane górskie',
    zone: 'drawers',
    category: 'Suche i sypkie',
    currentAmount: 350,
    totalAmount: 500,
    unit: 'g',
    expiryDate: addDays(180),
    kcalPer100g: 366,
    proteinPer100g: 13.5,
    fatPer100g: 7.0,
    carbsPer100g: 63.0,
    price: 3.99,
  },
  {
    id: 'p9',
    name: 'Makaron pełnoziarnisty Penne',
    zone: 'drawers',
    category: 'Suche i sypkie',
    currentAmount: 500,
    totalAmount: 500,
    unit: 'g',
    expiryDate: addDays(240),
    kcalPer100g: 348,
    proteinPer100g: 13.0,
    fatPer100g: 2.0,
    carbsPer100g: 66.0,
    price: 5.49,
  },
  {
    id: 'p10',
    name: 'Oliwa z oliwek Extra Virgin',
    zone: 'drawers',
    category: 'Sosy i przyprawy',
    currentAmount: 400,
    totalAmount: 500,
    unit: 'ml',
    expiryDate: addDays(300),
    kcalPer100g: 884,
    proteinPer100g: 0,
    fatPer100g: 100,
    carbsPer100g: 0,
    price: 28.00,
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Szakszuka z pomidorkami i ziołami',
    category: 'Śniadanie',
    prepTime: '15 min',
    kcal: 380,
    protein: 24,
    fat: 22,
    carbs: 18,
    description: 'Aromatyczne jajka sadzone w duszonych pomidorkach z czosnkiem, oliwą i świeżą bazylią.',
    ingredients: [
      { name: 'Jajka z wolnego wybiegu', amount: 3, unit: 'szt' },
      { name: 'Pomidorki koktajlowe', amount: 150, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
      { name: 'Czosnek świeży', amount: 1, unit: 'szt' },
    ],
    instructions: [
      'Rozgrzej oliwę na patelni i wrzuć przekrojone na pół pomidorki oraz posiekany czosnek.',
      'Smaż przez 4-5 minut aż zmiękną i puszczą sok.',
      'Zrób wgłębienia w sosie i wbij jajka.',
      'Przykryj patelnię pokrywką i gotuj na małym ogniu przez 4-6 minut aż białko się zetnie.',
      'Oprósz solą morską, pieprzem i podawaj na ciepło.'
    ],
  },
  {
    id: 'r2',
    title: 'Proteinowa owsianka z jogurtem i cynamonem',
    category: 'Śniadanie',
    prepTime: '10 min',
    kcal: 420,
    protein: 26,
    fat: 8,
    carbs: 62,
    description: 'Kremowa owsianka na ciepłym mleku z dodatkiem gęstego jogurtu, bogata w błonnik i białko.',
    ingredients: [
      { name: 'Płatki owsiane górskie', amount: 60, unit: 'g' },
      { name: 'Mleko 2.0% Świeże', amount: 150, unit: 'ml' },
      { name: 'Jogurt Grecki 0%', amount: 100, unit: 'g' },
    ],
    instructions: [
      'W małym rondelku zalej płatki owsiane mlekiem.',
      'Gotuj na małym ogniu przez ok. 5 minut, mieszając do uzyskania kremowej konsystencji.',
      'Przełóż do miseczki, wymieszaj z jogurtem greckim i posyp cynamonem.'
    ],
  },
  {
    id: 'r3',
    title: 'Puszyste placuszki bananowe',
    category: 'Śniadanie',
    prepTime: '15 min',
    kcal: 350,
    protein: 16,
    fat: 10,
    carbs: 48,
    description: 'Ekspresowe, delikatne placki z dojrzałych bananów i jajek bez dodatku cukru.',
    ingredients: [
      { name: 'Banan', amount: 1, unit: 'szt' },
      { name: 'Jajka z wolnego wybiegu', amount: 2, unit: 'szt' },
      { name: 'Płatki owsiane górskie', amount: 30, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 5, unit: 'ml' },
    ],
    instructions: [
      'Rozgnieć banana widelcem w misce na gładką masę.',
      'Dodaj jajka oraz płatki owsiane i dokładnie wymieszaj.',
      'Smaż małe placuszki na lekko natłuszczonej patelni po 2 minuty z każdej strony.'
    ],
  },
  {
    id: 'r4',
    title: 'Tosty z awokado i jajkiem sadzonym',
    category: 'Śniadanie',
    prepTime: '10 min',
    kcal: 410,
    protein: 18,
    fat: 22,
    carbs: 35,
    description: 'Chrupiące pieczywo pełnoziarniste z kremowym awokado, sokiem z cytryny i jajkiem.',
    ingredients: [
      { name: 'Chleb pełnoziarnisty', amount: 2, unit: 'szt' },
      { name: 'Awokado Hass', amount: 1, unit: 'szt' },
      { name: 'Jajka z wolnego wybiegu', amount: 2, unit: 'szt' },
    ],
    instructions: [
      'Opiecz kromki chleba w tosterze lub na patelni.',
      'Rozgnieć miąższ awokado z solą i pieprzem, rozsmaruj na pieczywie.',
      'Usmaż jajka sadzone i ułóż na tostach.'
    ],
  },
  {
    id: 'r5',
    title: 'Indyk z warzywami na patelni z makaronem',
    category: 'Obiad',
    prepTime: '25 min',
    kcal: 540,
    protein: 48,
    fat: 12,
    carbs: 58,
    description: 'Soczysta pierś z indyka duszona z chrupiącymi warzywami i makaronem pełnoziarnistym.',
    ingredients: [
      { name: 'Pierś z indyka (filet)', amount: 200, unit: 'g' },
      { name: 'Mieszanka warzyw na patelnię', amount: 200, unit: 'g' },
      { name: 'Makaron pełnoziarnisty Penne', amount: 70, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
    ],
    instructions: [
      'Ugotuj makaron al dente w osolonej wodzie.',
      'Pokrój indyka w kostkę i podsmaż na patelni z odrobiną oliwy.',
      'Dodaj warzywa i duś pod przykryciem ok. 8 minut.',
      'Połącz warzywa z mięsem i makaronem, dopraw ziołami prowansalskimi i papryką.'
    ],
  },
  {
    id: 'r6',
    title: 'Pieczony łosoś z cytryną i batatami',
    category: 'Obiad',
    prepTime: '30 min',
    kcal: 590,
    protein: 42,
    fat: 25,
    carbs: 48,
    description: 'Pożywny filet z łososia pieczony ze słodkimi batatami i świeżym rozmarynem.',
    ingredients: [
      { name: 'Filet z łososia', amount: 180, unit: 'g' },
      { name: 'Bataty', amount: 250, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
      { name: 'Cytryna', amount: 1, unit: 'szt' },
    ],
    instructions: [
      'Rozgrzej piekarnik do 190°C.',
      'Bataty obierz, pokrój w słupki, skrop oliwą i piecz przez 15 minut.',
      'Ułóż łososia obok batatów, skrop sokiem z cytryny i dopraw solą oraz pieprzem.',
      'Piecz całość jeszcze przez 12-14 minut.'
    ],
  },
  {
    id: 'r7',
    title: 'Spaghetti z mięsem mielonym i pomidorami',
    category: 'Obiad',
    prepTime: '30 min',
    kcal: 520,
    protein: 44,
    fat: 14,
    carbs: 56,
    description: 'Klasyczny sos pomidorowy z mielonym mięsem z indyka, czosnkiem i ziołami.',
    ingredients: [
      { name: 'Mięso mielone z indyka', amount: 200, unit: 'g' },
      { name: 'Passata pomidorowa', amount: 200, unit: 'ml' },
      { name: 'Makaron pełnoziarnisty Penne', amount: 70, unit: 'g' },
      { name: 'Czosnek świeży', amount: 2, unit: 'szt' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
    ],
    instructions: [
      'Podsmaż posiekany czosnek na oliwie, dodaj mielone mięso i smaż do zrumienienia.',
      'Wlej passatę pomidorową, dodaj oregano i bazylię, duś na wolnym ogniu przez 15 minut.',
      'Wymieszaj z ugotowanym makaronem.'
    ],
  },
  {
    id: 'r8',
    title: 'Risotto z pieczarkami i natką pietruszki',
    category: 'Obiad',
    prepTime: '25 min',
    kcal: 460,
    protein: 14,
    fat: 12,
    carbs: 72,
    description: 'Kremowy ryż duszony w bulionie z podsmażonymi pieczarkami i masłem.',
    ingredients: [
      { name: 'Ryż arborio lub biały', amount: 80, unit: 'g' },
      { name: 'Pieczarki świeże', amount: 150, unit: 'g' },
      { name: 'Masło ekstra', amount: 15, unit: 'g' },
      { name: 'Cebula', amount: 1, unit: 'szt' },
    ],
    instructions: [
      'Na maśle podsmaż posiekaną cebulę i pokrojone pieczarki.',
      'Dodaj suchy ryż i podsmażaj przez 2 minuty aż ziarna staną się szkliste.',
      'Stopniowo dolewaj gorącą wodę lub bulion, mieszając do miękkości ryżu.',
      'Dopraw solą, pieprzem i natką pietruszki.'
    ],
  },
  {
    id: 'r9',
    title: 'Gulasz drobiowy z kaszą gryczaną',
    category: 'Obiad',
    prepTime: '35 min',
    kcal: 490,
    protein: 45,
    fat: 11,
    carbs: 52,
    description: 'Sycące danie obiadowe: delikatne mięso z kurczaka w sosie warzywnym z paloną kaszą.',
    ingredients: [
      { name: 'Pierś z kurczaka', amount: 200, unit: 'g' },
      { name: 'Kasza gryczana', amount: 70, unit: 'g' },
      { name: 'Marchew', amount: 2, unit: 'szt' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
    ],
    instructions: [
      'Ugotuj kaszę gryczaną w osolonej wodzie.',
      'Mięso pokrój w kostkę i podsmaż na patelni z oliwą.',
      'Dodaj pokrojoną w plasterki marchewkę i podlej szklanką wody lub bulionu.',
      'Duś na wolnym ogniu pod przykryciem ok. 20 minut do miękkości warzyw.'
    ],
  },
  {
    id: 'r10',
    title: 'Krem z pieczonych pomidorów z bazylią',
    category: 'Zupa',
    prepTime: '25 min',
    kcal: 220,
    protein: 6,
    fat: 8,
    carbs: 30,
    description: 'Aksamitna zupa ze słodkich pomidorów z czosnkiem, oliwą i świeżą bazylią.',
    ingredients: [
      { name: 'Pomidorki koktajlowe', amount: 300, unit: 'g' },
      { name: 'Passata pomidorowa', amount: 200, unit: 'ml' },
      { name: 'Czosnek świeży', amount: 2, unit: 'szt' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
    ],
    instructions: [
      'W garnku rozgrzej oliwę i podsmaż czosnek oraz pomidory.',
      'Wlej passatę i 200 ml wody, gotuj na małym ogniu przez 15 minut.',
      'Zblenduj zupę na gładki krem i dopraw solą oraz bazylią.'
    ],
  },
  {
    id: 'r11',
    title: 'Rozgrzewająca zupa krem z dyni',
    category: 'Zupa',
    prepTime: '30 min',
    kcal: 260,
    protein: 5,
    fat: 12,
    carbs: 34,
    description: 'Krem z dyni hokkaido z nutą imbiru i mleczkiem.',
    ingredients: [
      { name: 'Dynia hokkaido', amount: 400, unit: 'g' },
      { name: 'Mleko 2.0% Świeże', amount: 150, unit: 'ml' },
      { name: 'Cebula', amount: 1, unit: 'szt' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 10, unit: 'ml' },
    ],
    instructions: [
      'Dynię pokrój w kostkę, cebulę posiekaj.',
      'Podsmaż cebulę na oliwie, dodaj dynię i zalej wodą do wysokości warzyw.',
      'Gotuj 20 minut, dolej mleko i zblenduj na krem.'
    ],
  },
  {
    id: 'r12',
    title: 'Krewetki smażone na oliwie z czosnkiem',
    category: 'Kolacja',
    prepTime: '15 min',
    kcal: 310,
    protein: 34,
    fat: 14,
    carbs: 6,
    description: 'Klasyczne danie: krewetki podsmażone w złocistej oliwie czosnkowej z pietruszką.',
    ingredients: [
      { name: 'Krewetki mrożone Black Tiger', amount: 180, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 15, unit: 'ml' },
      { name: 'Czosnek świeży', amount: 2, unit: 'szt' },
    ],
    instructions: [
      'Rozmroź i osusz krewetki ręcznikiem papierowym.',
      'Na patelni powoli rozgrzej oliwę z posiekanym czosnkiem.',
      'Zwiększ ogień, wrzuć krewetki i smaż po 2 minuty z każdej strony.',
      'Skrop sokiem z cytryny i podawaj od razu.'
    ],
  },
  {
    id: 'r13',
    title: 'Sałatka grecka z fetą i oliwkami',
    category: 'Kolacja',
    prepTime: '10 min',
    kcal: 290,
    protein: 12,
    fat: 21,
    carbs: 14,
    description: 'Orzeźwiająca sałatka ze świeżych warzyw z serem feta, oliwą i oregano.',
    ingredients: [
      { name: 'Ser Feta', amount: 100, unit: 'g' },
      { name: 'Pomidorki koktajlowe', amount: 150, unit: 'g' },
      { name: 'Ogórek zielony', amount: 1, unit: 'szt' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 15, unit: 'ml' },
    ],
    instructions: [
      'Pomidorki przekrój na połówki, ogórka pokrój w plasterki.',
      'Dodaj pokrojony w kostkę ser feta.',
      'Polej oliwą z oliwek, posyp oregano i delikatnie wymieszaj.'
    ],
  },
  {
    id: 'r14',
    title: 'Wrap pełnoziarnisty z tuńczykiem',
    category: 'Kolacja',
    prepTime: '10 min',
    kcal: 380,
    protein: 32,
    fat: 8,
    carbs: 45,
    description: 'Wygodny wrap z tuńczykiem w sosie własnym, kukurydzą i jogurtem greckim.',
    ingredients: [
      { name: 'Tortilla pełnoziarnista', amount: 1, unit: 'szt' },
      { name: 'Tuńczyk w sosie własnym', amount: 120, unit: 'g' },
      { name: 'Jogurt Grecki 0%', amount: 40, unit: 'g' },
      { name: 'Kukurydza konserwowa', amount: 40, unit: 'g' },
    ],
    instructions: [
      'Odsącz tuńczyka i wymieszaj z jogurtem greckim, solą i pieprzem.',
      'Na placku tortilli ułóż tuńczyka oraz kukurydzę.',
      'Zwiń ciasno w rulon i podpiecz chwilę na patelni z obu stron.'
    ],
  },
  {
    id: 'r15',
    title: 'Domowy hummus ze słupkami marchewek',
    category: 'Przekąska',
    prepTime: '10 min',
    kcal: 270,
    protein: 10,
    fat: 14,
    carbs: 26,
    description: 'Kremowa pasta z ciecierzycy, czosnku i oliwy, podawana z chrupiącą marchewką.',
    ingredients: [
      { name: 'Ciecierzyca gotowana', amount: 150, unit: 'g' },
      { name: 'Oliwa z oliwek Extra Virgin', amount: 15, unit: 'ml' },
      { name: 'Czosnek świeży', amount: 1, unit: 'szt' },
      { name: 'Marchew', amount: 2, unit: 'szt' },
    ],
    instructions: [
      'Ciecierzycę zblenduj na gładką pastę z czosnkiem, oliwą i 2 łyżkami wody.',
      'Dopraw solą, kuminem i sokiem z cytryny.',
      'Marchewki obierz i pokrój w słupki do maczania w hummusie.'
    ],
  },
  {
    id: 'r16',
    title: 'Fit pudding chia z musem malinowym',
    category: 'Deser',
    prepTime: '5 min',
    kcal: 240,
    protein: 8,
    fat: 10,
    carbs: 28,
    description: 'Lekki deser z nasion chia z mlekiem i warstwą owocowego musu.',
    ingredients: [
      { name: 'Nasiona chia', amount: 25, unit: 'g' },
      { name: 'Mleko 2.0% Świeże', amount: 150, unit: 'ml' },
      { name: 'Maliny mrożone lub świeże', amount: 80, unit: 'g' },
    ],
    instructions: [
      'Wymieszaj nasiona chia z mlekiem w szklance lub słoiczku.',
      'Wstaw do lodówki na minimum 2 godziny.',
      'Maliny rozgnieć na mus i wyłóż na wierzch puddingu przed podaniem.'
    ],
  },
];

export const INITIAL_SHOPPING: ShoppingItem[] = [
  {
    id: 's1',
    name: 'Jogurt Grecki 0%',
    amount: 400,
    unit: 'g',
    category: 'Nabiał',
    checked: false,
    isAuto: true,
    reason: 'Niski stan w spiżarni (< 25%)',
    price: 4.50,
  },
  {
    id: 's2',
    name: 'Czosnek świeży',
    amount: 2,
    unit: 'szt',
    category: 'Warzywa',
    checked: false,
    isAuto: true,
    reason: 'Brakujący składnik do przepisu: Krewetki smażone',
    price: 2.50,
  },
  {
    id: 's3',
    name: 'Kawa ziarnista Arabica',
    amount: 500,
    unit: 'g',
    category: 'Napoje',
    checked: true, // already in cart
    isAuto: false,
    price: 34.99,
  }
];

export const INITIAL_PLANNER: PlannedMealItem[] = [
  {
    id: 'm1',
    name: 'Proteinowa owsianka z jogurtem',
    amount: 250,
    unit: 'g',
    kcal: 420,
    protein: 26,
    fat: 8,
    carbs: 62,
    mealSlot: 'breakfast',
    date: formatDate(new Date()),
    isPantrySource: true,
  },
  {
    id: 'm2',
    name: 'Banan średni',
    amount: 1,
    unit: 'szt',
    kcal: 95,
    protein: 1.2,
    fat: 0.3,
    carbs: 23.5,
    mealSlot: 'second_breakfast',
    date: formatDate(new Date()),
    isPantrySource: false,
  }
];

export const INITIAL_GOALS: KitchenState['goals'] = {
  mode: 'auto',
  kcalGoal: 2150,
  proteinGoal: 135,
  fatGoal: 65,
  carbsGoal: 255,
  gender: 'female',
  weightKg: 64,
  heightCm: 168,
  age: 28,
  activityLevel: 1.55,
  goalType: 'maintain',
};

export const INITIAL_STATE: KitchenState = {
  pantry: INITIAL_PANTRY,
  recipes: INITIAL_RECIPES,
  planner: INITIAL_PLANNER,
  shoppingList: INITIAL_SHOPPING,
  customCategories: [],
  goals: INITIAL_GOALS,
};
